//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgłoszeniaPIWOlesno
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAZA_GOSPODARSTWA_
    {
        public Nullable<double> LP { get; set; }
        public string NR_STADA { get; set; }
        public Nullable<double> LICZBA_SZTUK { get; set; }
        public string IMIE_LUB_NAZWA_SKROCONA { get; set; }
        public string NAZWISKO_LUB_NAZWA { get; set; }
        public string GMINA { get; set; }
        public string MIEJSCOWOSC { get; set; }
        public string ULICA { get; set; }
        public Nullable<double> POSESJA { get; set; }
        public string LOKAL { get; set; }
        public string KOD_POCZTOWY { get; set; }
        public string POCZTA { get; set; }
    }
}
