//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZgłoszeniaPIWOlesno
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZGLOSZENIA_
    {
        public int ID { get; set; }
        public string NR_STADA { get; set; }
        public string TYP_STADA { get; set; }
        public double LICZBA_SZTUK { get; set; }
        public string NR_KOLCZYKA { get; set; }
        public string GATUNEK { get; set; }
        public string PLEC { get; set; }
        public System.DateTime DATA_URODZENIA { get; set; }
        public System.DateTime DATA_PADNIECIA { get; set; }
        public string GODZINA_PADNIECIA { get; set; }
        public string PRZYCZYNA { get; set; }
        public string OPIS_PRZYCZYNA { get; set; }
        public string KTO_ODBIERA { get; set; }
        public string OSOBA_ZGL { get; set; }
        public string ADRES_OSOBY_ZGL { get; set; }
        public string TEL_OSOBY_ZGL { get; set; }
        public string DATA_CZAS_ZGL { get; set; }
        public string KTO_PRZYJMUJE_ZGL { get; set; }
    }
}
